<% timestamp = Time.now.strftime("%Y%m%d_%H%M%S") %>

# Type of testrun
# default: -p html_report
# html_report: --format html --out=results/<%=timestamp%>_report.html

default: -p chrome -p json -p pretty -p html_report
ci: -p headless -p json -p pretty
firefox: BROWSER=firefox
chrome: BROWSER=chrome
headless: BROWSER=headless
json: --format message --out=results/logs/<%=timestamp%>_report.json
html_report: --format html --out=results/html/<%=timestamp%>_report.html
pretty: --format pretty
progress: --format progress